services:
  client:
    build:
      context: .
      cache_from:
        - type=local,src=build/docker-cache
      cache_to:
        - type=local,dest=build/docker-cache
      target: client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - ${CLIENT_PORT}:8080
    networks:
      - skynons
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}

  server:
    build:
      context: .
      cache_from:
        - type=local,src=build/docker-cache
      cache_to:
        - type=local,dest=build/docker-cache
      target: server
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    volumes:
      - blob-store:/data/blobs
    ports:
      - 127.0.0.1:${SERVER_PORT}:${SERVER_PORT}
    networks:
      - skynons
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${SERVER_PORT}
      - DB_EMBEDDED=false
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_PEPPER=${AUTH_PEPPER}
      - CONTINUATION_CONVERSATION_TIMEOUT=${CONTINUATION_CONVERSATION_TIMEOUT}

  db:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    networks:
      - skynons

volumes:
  db-data: {}
  blob-store: {}
networks:
  skynons:
    name: skynons_network
    driver: bridge
